### ISSUE TITLE
too much whitespace around graph in small panel.

### ISSUE THREAD

**Issue by bijwaard** [nline/nline-plotlyjs-panel#36]
Dear all,
First of all, thanks for this flexible plugin! One of the few options left to create flexible XY plots in grafana without Angular.
However, it does not take all space in my small panel.

My histogram type plot looks fine in edit mode:
![image](https://github.com/nline/nline-plotlyjs-panel/assets/6523124/c0171401-9937-4c34-adfa-99d7a28fef95)
But not in dashboard mode:
![image](https://github.com/nline/nline-plotlyjs-panel/assets/6523124/11695677-7d87-4311-adcc-de85456ee229)
When I enlarge the graph it gets visible, but still has much whitespace around it.
![image](https://github.com/nline/nline-plotlyjs-panel/assets/6523124/c2ebb2cd-b296-4031-bb5f-993623148136)

My layout looks like:
```
font:
  family: Inter, Helvetica, Arial, sans-serif
  color: rgb(25,27,31)
paper_bgcolor: white
plot_bgcolor: white
hoverlabel:
  bgcolor: white
xaxis:
  type: value
  autorange: true
  automargin: true
yaxis:
  type: log
  automargin: true
  autorange: true
```
Is there a way to use more of the panel height and width such that the graph is more visible?
I tried with automargin:false, but that does not seem to have any effect.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
After some fiddling I found the right layout parameters, guess they could be added to the examples...
```
margin:
  b: 0
  t: 0
  l: 0
  r: 0
legend:
  orientation: h
```
![image](https://github.com/nline/nline-plotlyjs-panel/assets/6523124/aef5801a-a175-4bec-baee-9bffc37b0c93)
