### ISSUE TITLE
Unable to create Violin plot

### ISSUE THREAD

**Issue by gregtayl** [nline/nline-plotlyjs-panel#37]
I'm trying to create a violin plot following the first Plotly.js example here: https://plotly.com/javascript/violin/

Unfortunately, the plot seems to expect an x-axis with a range of dates and instead of rendering the violin plot, it locks to a date range of Jan 2000 -> Jan 2001.

Here's the script I'm using (with hardcoded Y values):

```
const trace = {
  type: 'violin',
  y: [1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7, 7, 7, 10, 20, 30],
  points: 'none',
  box: {
    visible: true
  },
  boxpoints: false,
  line: {
    color: 'black'
  },
  fillcolor: '#8dd3c7',
  opacity: 0.6,
  meanline: {
    visible: true
  },
  x0: 'Total Bill'
};

return { 
  title: '',
  yaxis: {
    zeroline: false
  },
  data: [trace]
};
```

Here's the result:

![image](https://github.com/nline/nline-plotlyjs-panel/assets/5607078/433bbca3-5b76-4666-99c4-25ccff99807c)

**Comment by gregtayl** [comment]
Please disregard, the issue was in the layout configuration, xaxis had a type of date, switching this to string fixed the problem.

```
font:
  family: Inter, Helvetica, Arial, sans-serif
  color: rgb(25,27,31)
paper_bgcolor: white
plot_bgcolor: white
hoverlabel:
  bgcolor: white
xaxis:
  type: string
  autorange: true
  automargin: true
yaxis:
  automargin: true
  autorange: true
```
