### ISSUE TITLE
layout property doesn't seem to be accepting grafana variables for title.text property

### ISSUE THREAD

**Issue by apellew** [nline/nline-plotlyjs-panel#9]
The layout section is currently:
```
paper_bgcolor: rgba(0,0,0,0)
plot_bgcolor: rgba(150,150,150,0)
margin:
  t: 5
  r: 20
  b: 40
  l: 20
yaxis:
  automargin: true
  autorange: true
  color: rgba(150,150,150, 1)
  gridcolor: rgba(150,150,150, 0.2)
  range:
    - -0.00004907501471212626
    - 0.0009324252795303988
  showgrid: false
  showspikes: false
  type: linear
xaxis:
  autorange: true
  color: rgba(150,150,150, 1)
  gridcolor: rgba(150,150,150, 0.2)
  range:
    - 0
    - 2014.418722987175
  showgrid: false
  title:
    text: Hz
  type: linear
```
You see the x-axis has a title of Hz. The y-axis is either acceleration(g) or velocity(mm/s) data depending on a variable, varSpectrumType. What I'd like to do is add;
```
  title:
    text: variables.varSpectrumType
```
To the y-axis but, unfortunately, it just displays the text without doing the variable substitution.

I tried using `__from` (the grafana global variable) but it just displays "__from" as well. 

Is there any chance this could be added as an enhancement?
